### ISSUE TITLE
Bug: Can't hit enemies, enemies can't hit me.

### ISSUE THREAD

**Issue by Folset** [pnunes/Hexterminate#6] opened 2016-01-25 22:32 UTC
I am not sure how this happened or how I would replicate it, but it was happening long enough to mess about trying to find the screentogif recorder and then try get a good shot of it twice. Never got a single point of damage and couldn't clear the system because of it.

https://gfycat.com/UniformQuestionableCreature

I had a shield that was depleted, two module repairers, a missile interceptor and a fuel injector. The fuel injector was currently activated and I had used both the module repairers multiple times. Don't know if that helps.

**Comment by pnunes** [comment] 2016-01-26 08:33
Thanks! I know what the issue is. Although the game happens on a 2D plane, it is actually 3D. Normally the ships remain in the game plane but on occasion the collision between ships can cause them to drift vertically, at which point projectiles will no longer hit them. I'll sort that out.

**Comment by pnunes** [comment] 2016-05-06 15:11
Fixed on 0.8.0.

**Closed by pnunes** 2016-05-06 15:11 UTC
Labels: bug
